export const CATEGORIES_INDEX         = '@@CATEGORIES_INDEX'
export const CATEGORIES_CREATE        = '@@CATEGORIES_CREATE'
export const CATEGORIES_UPDATE        = '@@CATEGORIES_UPDATE'
export const CATEGORIES_SHOW          = '@@CATEGORIES_SHOW'
export const CATEGORY_MOVE            = '@@CATEGORY_MOVE'
export const CATEGORIES_CHANGE_ORDER  = '@@CATEGORIES_CHANGE_ORDER'
export const CATEGORY_SELECT          = '@@CATEGORY_SELECT'
export const CATEGORY_DESTROY         = '@@CATEGORY_DESTROY'
export const CATEGORY_DIALOG_OPEN     = '@@CATEGORY_DIALOG_OPEN'

export const DISHES_CREATE            = '@@DISHES_CREATE'
export const DISH_UPDATE              = '@@DISH_UPDATE'
export const DISH_SELECT              = '@@DISH_SELECT'
export const DISH_DIALOG_OPEN         = '@@DISH_EDIT'
export const DISH_DESTROY             = '@@DISH_DESTROY'
export const DISH_MOVE                = '@@DISH_MOVE'
export const DISHES_CHANGE_ORDER      = '@@DISHES_CHANGE_ORDER'
