export const CATEGORIES_INDEX         = '@@CATEGORIES_INDEX'
export const CATEGORIES_CREATE        = '@@CATEGORIES_CREATE'
export const CATEGORIES_UPDATE        = '@@CATEGORIES_UPDATE'
export const CATEGORIES_SHOW          = '@@CATEGORIES_SHOW'
export const CATEGORY_MOVE            = '@@CATEGORY_MOVE'
export const CATEGORIES_CHANGE_ORDER  = '@@CATEGORIES_CHANGE_ORDER'
export const CATEGORY_EDIT            = '@@CATEGORY_EDIT'
export const CATEGORY_SELECT          = '@@CATEGORY_SELECT'
export const CATEGORY_DESTROY         = '@@CATEGORY_DESTROY'
export const CATEGORY_NEW_SHOW        = '@@CATEGORY_NEW_SHOW'

export const DISHES_CREATE            = '@@DISHES_CREATE'
export const DISH_UPDATE              = '@@DISH_UPDATE'
export const DISH_EDIT                = '@@DISH_EDIT'
export const DISH_DESTROY             = '@@DISH_DESTROY'
