export const BLOGS_CREATE             = '@@BLOGS_CREATE'
export const BLOGS_INDEX              = '@@BLOGS_INDEX'
export const BLOGS_SHOW               = '@@BLOGS_SHOW'
export const BLOGS_DESTROY            = '@@BLOGS_DESTROY'
export const BLOG_SELECT              = '@@BLOG_SELECT'