export const NEWS_CREATE             = '@@NEWS_CREATE'
export const NEWS_INDEX              = '@@NEWS_INDEX'
export const NEWS_SHOW               = '@@NEWS_SHOW'
export const NEWS_DESTROY            = '@@NEWS_DESTROY'
export const NEWS_SELECT             = '@@NEWS_SELECT'